### ISSUE TITLE
How to get the LiDAR - Front View (depth)

### ISSUE THREAD

**Issue by LIUQI-creat** [open-pack/openpack-toolkit#11]
hello,
@getty708  Thanks for the brilliant challenge. I have some problems with dataset downloading:

1. How to get the LiDAR - Front View (depth) ? Is the LiDAR data  unavailable in this challenge ?
2. About Kinect and RealSense data from google drive, many folders are nested after decompression. How should I place them correctly？

Thank you very much!

**Comment by getty708** [comment]
Hello @LIUQI-creat,
Thank you for sharing your problem.

> 1. How to get the LiDAR - Front View (depth) ? Is the LiDAR data unavailable in this challenge ?

LiDAR data is also available in Google Drive. (e.g., [GoogleDrive:/v0.3.0/U0105/lidar/](https://drive.google.com/drive/folders/1fpf5U5akm0h5S7Pw7CN-VEs7DzmFxTtL?usp=share_link))

However, the data of some sessions are missing or broken.
Please check the availability before you use 🙇 


> 2. About Kinect and RealSense data from google drive, many folders are nested after decompression. How should I place them correctly？

Please unzip the downloaded files in the path in Google Drive.
For example, when you download [`U0101/kinect/depth/frames/S0100.zip`](https://drive.google.com/drive/folders/1l-DrqvCHetj3yUcRTuiA4Wx_VxfJXsR8?usp=share_link), please unzip and place folder `S0100` in the `U0101/kinect/depth/frames/`.

If you want to download all the files, please check this issue #10 first.
I implemented a tool for downloading and unzipping for Google Drive.

Thank you and please enjoy our competition!

**Comment by getty708** [comment]
@LIUQI-creat  
Here is a list of known issues. I hope it will help you.

https://github.com/open-pack/openpack-toolkit/blob/main/docs/USER.md#recording-errors
