### ISSUE TITLE
 About image size 

### ISSUE THREAD

**Issue by freedom1810** [open-pack/openpack-toolkit#6]
I dont see any information about image size when I use pose data, can you update it?

**Comment by getty708** [comment]
@freedom1810 

Sorry for the late reply.
And thank you for your valuable comment.

Here is information about the image size. 
This is just a quick note. I will confirm again and 
I will update this information in the next update.

- Keypoint (RGB):
  - 1280 x 720 
  - (For U0201-S0100/S0200/S0300 ... 1920 x 1080)*
- Depth Image: 640 x 576  

NOTE: We made mistakes with the Kinect configuration for U0201. The data of this user is not released yet.  So please just ignore it.
