### ISSUE TITLE
About submission error

### ISSUE THREAD

**Issue by xxxLuiu** [open-pack/openpack-toolkit#8]
Hi,
This is a very interesting task.
I tried to submit my own results on final phase, but got the following error:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
INFO:__main__:args: Namespace(input_dir=PosixPath('/tmp/codalab/tmpaUSMXn/run/input'), output_dir=PosixPath('/tmp/codalab/tmpaUSMXn/run/output'))
DEBUG:__main__:load /tmp/codalab/tmpaUSMXn/run/input/res/submission.json
INFO:__main__:phase=FINAL
DEBUG:__main__:load reference data from /tmp/codalab/tmpaUSMXn/run/input/ref/reference_data/U0104/S0100.csv
DEBUG:__main__:ts_head=1637032675000, ts_tail=1637035675000
DEBUG:__main__:ind=(3001,), unixtime_pred=(3008,), prediction=(3008,)
DEBUG:__main__:load reference data from /tmp/codalab/tmpaUSMXn/run/input/ref/reference_data/U0104/S0300.csv
DEBUG:__main__:ts_head=1637044251000, ts_tail=1637046524000
DEBUG:__main__:ind=(2274,), unixtime_pred=(2280,), prediction=(2280,)
DEBUG:openpack_toolkit.codalab.operation_segmentation.eval:drop ignore classs samples (ID=8100)
DEBUG:openpack_toolkit.codalab.operation_segmentation.eval:  Befoe: t=(5275,), y=(5275,)
DEBUG:openpack_toolkit.codalab.operation_segmentation.eval:  After: t=(5127,), y=(5127,)
/tmp/codalab/tmpaUSMXn/run/program/openpack_toolkit/codalab/operation_segmentation/eval.py:58: UserWarning: ignore_class_id (ID8100) exists in y_id.
  f"ignore_class_id (ID{ignore_class_id}) exists in y_id.")
/tmp/codalab/tmpaUSMXn/run/program/openpack_toolkit/codalab/operation_segmentation/eval.py:75: UserWarning: y_id includes unknown class IDs. expected class IDs are (100, 200, 300, 400, 500, 600, 700, 800, 900, 1000), but got {800, 100, 8100, 900, 200, 1000, 300, 400, 500, 600, 700}.
  "y_id includes unknown class IDs. "
DEBUG:__main__:load reference data from /tmp/codalab/tmpaUSMXn/run/input/ref/reference_data/U0108/S0100.csv
DEBUG:__main__:ts_head=1639011965000, ts_tail=1639014118000
DEBUG:__main__:ind=(2154,), unixtime_pred=(2158,), prediction=(2158,)
DEBUG:__main__:load reference data from /tmp/codalab/tmpaUSMXn/run/input/ref/reference_data/U0108/S0200.csv
DEBUG:__main__:ts_head=1639015324000, ts_tail=1639017667000
DEBUG:__main__:ind=(2344,), unixtime_pred=(2349,), prediction=(2349,)
DEBUG:__main__:load reference data from /tmp/codalab/tmpaUSMXn/run/input/ref/reference_data/U0108/S0300.csv
DEBUG:__main__:ts_head=1639018831000, ts_tail=1639020910000
DEBUG:__main__:ind=(2080,), unixtime_pred=(2084,), prediction=(2084,)
DEBUG:__main__:load reference data from /tmp/codalab/tmpaUSMXn/run/input/ref/reference_data/U0108/S0500.csv
DEBUG:__main__:ts_head=1639028558000, ts_tail=1639030618000
DEBUG:__main__:ind=(2061,), unixtime_pred=(2067,), prediction=(2067,)
DEBUG:openpack_toolkit.codalab.operation_segmentation.eval:drop ignore classs samples (ID=8100)
DEBUG:openpack_toolkit.codalab.operation_segmentation.eval:  Befoe: t=(8639,), y=(8639,)
DEBUG:openpack_toolkit.codalab.operation_segmentation.eval:  After: t=(8462,), y=(8462,)
/tmp/codalab/tmpaUSMXn/run/program/openpack_toolkit/codalab/operation_segmentation/eval.py:75: UserWarning: y_id includes unknown class IDs. expected class IDs are (100, 200, 300, 400, 500, 600, 700, 800, 900, 1000), but got {800, 900, 8100, 100, 200, 1000, 300, 400, 500, 600, 700}.
  "y_id includes unknown class IDs. "
DEBUG:__main__:load reference data from /tmp/codalab/tmpaUSMXn/run/input/ref/reference_data/U0110/S0100.csv
DEBUG:__main__:ts_head=1640138287000, ts_tail=1640140080000
DEBUG:__main__:ind=(1794,), unixtime_pred=(1799,), prediction=(1799,)
DEBUG:__main__:load reference data from /tmp/codalab/tmpaUSMXn/run/input/ref/reference_data/U0110/S0200.csv
DEBUG:__main__:ts_head=1640141341000, ts_tail=1640142793000
DEBUG:__main__:ind=(1453,), unixtime_pred=(1460,), prediction=(1460,)
DEBUG:__main__:load reference data from /tmp/codalab/tmpaUSMXn/run/input/ref/reference_data/U0110/S0300.csv
DEBUG:__main__:ts_head=1640146710000, ts_tail=1640148181000
DEBUG:__main__:ind=(1472,), unixtime_pred=(1479,), prediction=(1479,)
DEBUG:__main__:load reference data from /tmp/codalab/tmpaUSMXn/run/input/ref/reference_data/U0110/S0400.csv
DEBUG:__main__:ts_head=1640149379000, ts_tail=1640150797000
DEBUG:__main__:ind=(1419,), unixtime_pred=(1425,), prediction=(1425,)
DEBUG:__main__:load reference data from /tmp/codalab/tmpaUSMXn/run/input/ref/reference_data/U0110/S0500.csv
DEBUG:__main__:ts_head=1640151996000, ts_tail=1640153335000
DEBUG:__main__:ind=(1340,), unixtime_pred=(1346,), prediction=(1346,)
DEBUG:openpack_toolkit.codalab.operation_segmentation.eval:drop ignore classs samples (ID=8100)
DEBUG:openpack_toolkit.codalab.operation_segmentation.eval:  Befoe: t=(7478,), y=(7478,)
DEBUG:openpack_toolkit.codalab.operation_segmentation.eval:  After: t=(7401,), y=(7401,)
/tmp/codalab/tmpaUSMXn/run/program/openpack_toolkit/codalab/operation_segmentation/eval.py:75: UserWarning: y_id includes unknown class IDs. expected class IDs are (100, 200, 300, 400, 500, 600, 700, 800, 900, 1000), but got {800, 8100, 100, 900, 200, 1000, 300, 400, 500, 600, 700}.
  "y_id includes unknown class IDs. "
DEBUG:__main__:load reference data from /tmp/codalab/tmpaUSMXn/run/input/ref/reference_data/U0203/S0100.csv
DEBUG:__main__:ts_head=1646787682000, ts_tail=1646789848000
DEBUG:__main__:ind=(2166,), unixtime_pred=(2186,), prediction=(2186,)
Traceback (most recent call last):
  File "/tmp/codalab/tmpaUSMXn/run/program/evaluate.py", line 226, in 
    main(args.input_dir, args.output_dir)
  File "/tmp/codalab/tmpaUSMXn/run/program/evaluate.py", line 180, in main
    unixtime_pred_sess, unixtime_gt_sess)
  File "/opt/conda/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 904, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/opt/conda/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 752, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(shapes (2166,), (2167,) mismatch)
 x: array([1646787682000, 1646787683000, 1646787684000, ..., 1646789846000,
       1646789847000, 1646789848000])
 y: array([1646787682000, 1646787683000, 1646787684000, ..., 1646789846000,
       1646789847000, 1646789848000])

I will be very appreciate if you can help me fix this error!

**Comment by getty708** [comment]
@xxxLuiu Thank you for your participation in this challenge! I'm really pleased to hear your words!
I'm also happy to help you.

```bash
AssertionError:
Arrays are not equal

(shapes (2166,), (2167,) mismatch)
x: array([1646787682000, 1646787683000, 1646787684000, ..., 1646789846000,
1646789847000, 1646789848000])
y: array([1646787682000, 1646787683000, 1646787684000, ..., 1646789846000,
1646789847000, 1646789848000])
```

This error indicates that one timeslot is missing in for submission.
The required time-series length is `2167`, but you only have `2166`.

Could you compute the diff of the timestamps like this?

```python
unixtimes = submission_dict["U0203-S0100"]["unixtime"]
delta = unixtime[1:] - unixtime[:-1]

ind = np.where(delta != 1000)[0]
print(ind)
assert len(ind) == 0
```

**Comment by freedom1810** [comment]
@xxxLuiu it because you use only pose data, sometime pose data can't be detected and you will miss predict action in this timestamp

**Comment by shubhamwagh** [comment]
How do you go about solving this issue?

**Comment by getty708** [comment]
Sorry for the late reply.
Did you fix this problem? I want to see solutions from participants.

Time slots are set every 1 second. So you can use [pandas.DataFrame.asfreq](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.asfreq.html).

Here is a sample pseudo code.

```python
df = pd.DataFrame({
  "unixtime": submission_dict["U0203-S0100"]["unixtime"],
  "prediction": submission_dict["U0203-S0100"]["prediction"],
})

# Set datetime data to index.
df["time"] = pd.to_datetime(df["unixtime"].astype(int), unit="ms")
df = df.set_index("time")

# Resample (to interpolate missing values with the previous data)
df = df.asfreq(freq='1S', method='ffill')
```

**Comment by getty708** [comment]
@shubhamwagh Thank you for your suggestion. I created a new issue.

(Nowadays, I'm in busy mode because of my thesis and other stuff. The changes will be available after February. 🙇 )
